{% set dataset_name = "SAIDDATA" %}
{% set version = "2.0" %}
{% set sha256 = "1d26a8e79baa71e44d5759b9f55a67e8b7ede31751316a9e9037d80090c72e91" %}
{% set env_var = "G4SAIDXSDATA" %}
{% set summary = "GEANT4 data files from evaluated cross-sections in SAID data-base" %}

{% set name = "geant4-data-"+dataset_name.lower() %}
{% set install_dir = "share/Geant4/data/"+dataset_name+version %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://geant4-data.web.cern.ch/geant4-data/datasets/G4{{ dataset_name }}.{{ version }}.tar.gz
    sha256: {{ sha256 }}
    folder: dataset

build:
    number: 1
    noarch: generic
    script:
        - mkdir -p ${PREFIX}/{{ install_dir }}
        - cp -r dataset/* ${PREFIX}/{{ install_dir }}
        - ${RECIPE_DIR}/create_activation_scripts.sh {{ name }} {{ env_var }} {{ install_dir }}

# Conda-forge is unable to build packages that have no dependencies so add
# `make` as a dummy build dependency
requirements:
  build:
    - make

test:
    commands:
        - "[ \"${{ env_var }}\" == \"$CONDA_PREFIX/{{ install_dir }}\" ]"

about:
    home: https://geant4.web.cern.ch/
    summary: '{{ summary }}'
    license: OTHER
    license_file: CREDIT

extra:
    recipe-maintainers:
        - chrisburr
        - tkittel
