travis:
  secure:
    BINSTAR_TOKEN: l83/FIZglJxaDKU6cu3JWSuZxLlY/IinRvVrbmkAiv0t1kEUYBK35lLPMWQiyAEe68w6zpuWkGA4UyHR7BYGVEi1LTBJB3SLmpLvMMFSoYr+1DGfWQbF+2eOCkFaY1bpISAp0ucb1oDpb4j7RNfKd5y21BdA6/n3QLD73kdGeM+dk0ViXFrfa/tLfQPqrzZOuEssJ0Xu/MnLHZ/PudCrKAE3qDbdZM+XkGaG1cIo7oaa9wqgvy4mQ136GrWnYA3gHs2RP/15von94BQ7c/ypC+Plxv36fKNkdvZzd7qPF9bAfY/gbXXHaTFZRCxT54/OPf2XOeu/KhDXo/ilugACT7wp29sgfYD1KzUpptumWFTq2Vv4g0yJKFHVuvGz65w2ynw9cxqBUQpukkzWq7Zs2D1QzVOOU8HlU8GYAXAt2nDrGWhqCvwOYJrPMLNxwR3nMYfZt8uhi29yP1KIJSlog0SecVSYsvY1khbcTCJHmFTCWmjQu1eY7HAjvRMs9s/8sJiB5o/QbZh/SklnGhEVp8+3zL6g7mpelpktqZa6kR7Jy/yuXXAYvi5wTVDGdAlvM8XfUkIK3I8FgUmjJs6zTj9CbUmmfZZGcTKtewf/YiVs+pOstoODX7+nnwCKhyoTsoAjrpm8kw6HnTyeqFoWcok2l+ZtrHWs78kuNHyUc4w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
