travis:
  secure:
    BINSTAR_TOKEN: cRDZX4M2/0nTB663/mlM85gvvt7VKu3iYqvv+HsboWACiU7v67nLKh25Yy1OwlOZ0CGmhCKiSe6ITw+/g9kn2u+qyuPVfDBZu11+pbCSrlX1i2LEtbIuzap8KyrB2mrSofufkppMbj9tuS50ei9C3nqGbFJIgORec9yC5N+2gWuFgw7+eeVn6Zhu3z7XMvKnMAYqkqNLjLkWAAraPtWD5GWShEXVYvS2Is7vKvTmKJBWPJc0FrGQUp6TXTbndm7ZKWCQsMNqcuUSCKvcj4eMK8SiAo/nLf1g5o1++9h4Hexwdf/O883lcMqWGrmYqOKZPsm4+Sg4Cdac3dMrG++S7mTlCfbQIPeb7ViHLH5475yI/CHvcJBLMmfcQNX9EwgcrywrlzqJTyY6mUMBNPKKEaUyHPCa0Tfl8UUZcU1TX/EcX8AG1U0lwIF29EUikGCkj18O6uy8NwH10aWRk3xb/EGuunUI8GJcTz9gJBFlECJCc+otjHRNbgqtMmrF4/uN2kKI3q2einFPdW81aqDs8354pnxE0if82hIywDdhaPfdFCIi02XneM68fWiqYorcw6IEICmUSQ/oGr2RZokkkm9tOOY9cuM5CVWQAIU2X8DBbpsi7rN1oAFpT0KYvLztkNY0B2Btho9t36cagtcpv9FIv16i7ns72p44UjVxMQA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
