travis:
  secure:
    BINSTAR_TOKEN: ncK00yBiDT/HVxvU4BFZUm2Y/IKwzykxgUnPFd4jH4RCjh3R7w2tWJUZGE5o+KF1uNrgl4oTfBfWFcbhKPjcsRYiKQ5zTK2Y/iWIWkqhi0gyngUjslzicdsvnzHQzNgzrinZDHZT8a7vd71tfakZQ24I60jizRk5wOWcGENfTZcjHjoXBX5DZ4iegT0CH5s9lsW90L5Id3Yf/dWyszlCMdEUG/ocIUz9Lw9SxauQX4MNxbhcsOo8pIKyz7L2Fp+TPdUWNMTQKOJ4qGVw4iP46dhMyGA8igdWDMmg3Mo+OxItLKIRq1/W8oL8LEm8tIkDc+KU9v/9WVHYzLV68r2ioTnYYAqGSUbbL/pcUu73HD5DX32Ps7PJLR2ivSlv773ci5ums07lcCV8LXLuhNpWNb+gAzyQVT8lr7j0GqrjOgjPsqFz5RCtFHdGKp8n2qAAWWSnv/sxdFR4u2mAf1iTwwMJsX9cV/Yzrfq3+WWCpbWFIeERWCiJDnIO3gd/JvWVG/LWs1i9+yUZ28c7Tn+ejeSm3exumwrK1r42DxT0bVmcNGv+a0nmFX4UVuywq6WrusLDG4i2eqr4o90cZuApRhngGQVI84iNwjlhb2epYD14kS8fdKCT/tp82SkIbU+qsmyi4mWs9duOpw2A/FZFxDAQA3eerWPSfKIKc+ketmY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
